startDelaySeconds: 0
lowercaseOutputName: true
lowercaseOutputLabelNames: true

rules:
  - pattern: "metrics:name=(.+),type=gauges"
    name: spark_$1
    type: GAUGE

  - pattern: "metrics:name=(.+),type=counters"
    name: spark_$1_total
    type: COUNTER
